# Stream Security OCI integration - Resource Manager stack v1.1.2
#
# Fully automated onboarding: Stream Security generates the API keypair
# server-side, sends the PUBLIC half via zipUrlVariables, this stack uploads
# it as the new IAM user's API key. An OCI Events rule fires on
# CreateApiKey, routes the event through OCI Notifications, which POSTs to
# Stream Security's auto-ack webhook. Customer clicks Apply and walks away.
#
# Ordering note: the api_key creation MUST happen AFTER the Notifications
# subscription has been confirmed by Stream Security's webhook. OCI drops
# messages sent to PENDING subscriptions and does not replay them once
# confirmed. We use time_sleep to give the confirmation handshake time to
# complete before the api_key fires its event.

terraform {
  required_version = ">= 1.3"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = ">= 5.0.0"
    }
    time = {
      source  = "hashicorp/time"
      version = ">= 0.9.0"
    }
  }
}

# Resource Manager auto-populates these from the launching user's session.
variable "tenancy_ocid" {
  type        = string
  description = "Tenancy OCID (auto-populated by Resource Manager)."
}

variable "current_user_ocid" {
  type        = string
  description = "Launching user's OCID (auto-populated by Resource Manager; unused)."
}

variable "region" {
  type        = string
  description = "OCI region (auto-populated by Resource Manager)."
}

# Passed by Stream Security wizard via zipUrlVariables.
variable "external_id" {
  type        = string
  description = "Stream Security account identifier."
}

variable "account_token" {
  type        = string
  sensitive   = true
  description = "Stream Security per-account token (echoed in outputs)."
}

variable "public_key" {
  type        = string
  description = "PEM-encoded RSA public key generated by Stream Security; uploaded as the API key."
}

variable "acknowledge_url" {
  type        = string
  description = "Stream Security auto-ack HTTPS endpoint (with account_token in path)."
}

provider "oci" {
  region = var.region
}

# ---------------------------------------------------------------------------
# IAM: read-only user + group + policy
# ---------------------------------------------------------------------------

resource "oci_identity_group" "stream_security_readers" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-readers-${var.external_id}"
  description    = "Stream Security read access."
}

resource "oci_identity_user" "stream_security_api_user" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-api-${var.external_id}"
  description    = "API-only user used by Stream Security to scan this tenancy."
  email          = "noreply+${var.external_id}@stream.security"
}

resource "oci_identity_user_group_membership" "stream_security_membership" {
  user_id  = oci_identity_user.stream_security_api_user.id
  group_id = oci_identity_group.stream_security_readers.id
}

resource "oci_identity_policy" "stream_security_read_policy" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-read-policy-${var.external_id}"
  description    = "Read-only access for Stream Security."
  statements = [
    "Allow group ${oci_identity_group.stream_security_readers.name} to inspect all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read audit-events in tenancy",
  ]
}

# ---------------------------------------------------------------------------
# Auto-ack: Notifications Topic + HTTPS subscription + Events rule
# ---------------------------------------------------------------------------

resource "oci_ons_notification_topic" "stream_security_topic" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-ack-${var.external_id}"
  description    = "Stream Security onboarding callback topic."
}

resource "oci_ons_subscription" "stream_security_ack" {
  compartment_id = var.tenancy_ocid
  topic_id       = oci_ons_notification_topic.stream_security_topic.id
  protocol       = "CUSTOM_HTTPS"
  endpoint       = var.acknowledge_url
}

# Wait for the subscription confirmation handshake before creating the
# api_key. OCI Notifications sends a SubscriptionConfirmation POST to our
# webhook the moment oci_ons_subscription is created; our endpoint GETs the
# ConfirmationURL synchronously. The whole roundtrip is < 5 seconds in
# practice, but we wait 60s to absorb retries on the first POST.
resource "time_sleep" "wait_for_subscription_confirmation" {
  depends_on      = [oci_ons_subscription.stream_security_ack]
  create_duration = "60s"
}

# Events rule that forwards CreateApiKey for our specific user to the topic.
# We filter on data.additionalDetails.userId — data.resourceName in a
# CreateApiKey event is the api_key OCID, not the user name.
resource "oci_events_rule" "stream_security_apikey_created" {
  compartment_id = var.tenancy_ocid
  display_name   = "stream-security-apikey-created-${var.external_id}"
  description    = "Forward Stream Security user's CreateApiKey events to the ack topic."
  is_enabled     = true
  condition = jsonencode({
    eventType = ["com.oraclecloud.identityControlPlane.CreateApiKey"]
    data = {
      additionalDetails = {
        userId = [oci_identity_user.stream_security_api_user.id]
      }
    }
  })
  actions {
    actions {
      action_type = "ONS"
      is_enabled  = true
      topic_id    = oci_ons_notification_topic.stream_security_topic.id
    }
  }
  depends_on = [time_sleep.wait_for_subscription_confirmation]
}

# api_key creation triggers the CreateApiKey event that the rule routes to
# the topic. Must be AFTER the events rule is active so the event isn't
# dropped, and after the subscription is confirmed so the topic can deliver.
resource "oci_identity_api_key" "stream_security_api_key" {
  user_id    = oci_identity_user.stream_security_api_user.id
  key_value  = var.public_key
  depends_on = [oci_events_rule.stream_security_apikey_created]
}

# ---------------------------------------------------------------------------
# Outputs (auto-ack handles everything; informational fallback only).
# ---------------------------------------------------------------------------

output "stream_security_user_ocid" {
  value       = oci_identity_user.stream_security_api_user.id
  description = "OCI user OCID - Stream Security receives this automatically."
}

output "stream_security_fingerprint" {
  value       = oci_identity_api_key.stream_security_api_key.fingerprint
  description = "API key fingerprint - Stream Security receives this automatically."
}

output "stream_security_status" {
  value       = "Auto-ack subscription created and api_key uploaded. Stream Security should mark the integration READY within ~1 minute."
  description = "Status hint for the customer."
}
