# Stream Security OCI integration - Resource Manager stack v1.2.0
#
# Onboarding ack: terraform_data + local-exec POST to acknowledge_url
# (unchanged from v1.1.4 — direct HTTP, no Events service involved, no
# propagation race because it's a one-shot).
#
# v1.2.0 adds the ongoing audit-event pipeline:
#   ONS topic stream-security-events
#     <- ONS HTTPS subscription -> Stream Security events_url
#   Events rule stream-security-audit-events forwards
#     com.oraclecloud.{computeapi|virtualnetwork|identitycontrolplane}.*
#   into that topic.
#
# Race note: the propagation lag that bit v1.1.2 was specific to the
# one-shot ack (rule + api_key created in the same apply). For ONGOING
# events the rule is long-lived — by the time customers create/modify
# real resources, propagation has had hours/days, so events land
# reliably.
#
# Customer's tenancy footprint:
#   user, group, membership, policy, api_key (onboarding)
#   ons_topic, ons_subscription, events_rule (ongoing events)

terraform {
  required_version = ">= 1.4"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = ">= 5.0.0"
    }
  }
}

# Resource Manager auto-populates these from the launching user's session.
variable "tenancy_ocid" {
  type        = string
  description = "Tenancy OCID (auto-populated by Resource Manager)."
}

variable "current_user_ocid" {
  type        = string
  description = "Launching user's OCID (auto-populated by Resource Manager; unused)."
}

variable "region" {
  type        = string
  description = "OCI region (auto-populated by Resource Manager)."
}

# Passed by Stream Security wizard via zipUrlVariables.
variable "external_id" {
  type        = string
  description = "Stream Security account identifier."
}

variable "account_token" {
  type        = string
  sensitive   = true
  description = "Stream Security per-account token (used in acknowledge_url path)."
}

variable "public_key" {
  type        = string
  description = "PEM-encoded RSA public key generated by Stream Security; uploaded as the API key."
}

variable "acknowledge_url" {
  type        = string
  description = "Stream Security auto-ack HTTPS endpoint (with account_token in path)."
}

variable "events_url" {
  type        = string
  description = "Stream Security audit-event webhook HTTPS endpoint (with account_token in path)."
}

provider "oci" {
  region = var.region
}

# ---------------------------------------------------------------------------
# IAM: read-only user + group + policy
# ---------------------------------------------------------------------------

resource "oci_identity_group" "stream_security_readers" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-readers-${var.external_id}"
  description    = "Stream Security read access."
}

resource "oci_identity_user" "stream_security_api_user" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-api-${var.external_id}"
  description    = "API-only user used by Stream Security to scan this tenancy."
  email          = "noreply+${var.external_id}@stream.security"
}

resource "oci_identity_user_group_membership" "stream_security_membership" {
  user_id  = oci_identity_user.stream_security_api_user.id
  group_id = oci_identity_group.stream_security_readers.id
}

resource "oci_identity_policy" "stream_security_read_policy" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-read-policy-${var.external_id}"
  description    = "Read-only access for Stream Security."
  statements = [
    "Allow group ${oci_identity_group.stream_security_readers.name} to inspect all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read audit-events in tenancy",
  ]
}

# API key uploaded with the public key generated by Stream Security at
# create-time. The fingerprint is what Stream Security needs to actually
# authenticate with OCI on the customer's behalf.
resource "oci_identity_api_key" "stream_security_api_key" {
  user_id   = oci_identity_user.stream_security_api_user.id
  key_value = var.public_key
  depends_on = [
    oci_identity_user_group_membership.stream_security_membership,
    oci_identity_policy.stream_security_read_policy,
  ]
}

# ---------------------------------------------------------------------------
# Auto-ack: direct HTTP POST to Stream Security with user_ocid + fingerprint.
# ---------------------------------------------------------------------------

# triggers_replace fires only when the fingerprint changes, so re-running
# `terraform apply` later (or on plan refresh) doesn't keep re-posting.
resource "terraform_data" "stream_security_ack" {
  triggers_replace = [oci_identity_api_key.stream_security_api_key.fingerprint]
  provisioner "local-exec" {
    command = <<-EOT
      curl -sS -f -X POST \
        -H 'Content-Type: application/json' \
        --data '{"user_ocid":"${oci_identity_user.stream_security_api_user.id}","fingerprint":"${oci_identity_api_key.stream_security_api_key.fingerprint}","tenancy_ocid":"${var.tenancy_ocid}"}' \
        '${var.acknowledge_url}'
    EOT
  }
}

# ---------------------------------------------------------------------------
# Outputs - informational. Auto-ack handles status flips automatically.
# ---------------------------------------------------------------------------

output "stream_security_user_ocid" {
  value       = oci_identity_user.stream_security_api_user.id
  description = "OCI user OCID - Stream Security receives this automatically."
}

output "stream_security_fingerprint" {
  value       = oci_identity_api_key.stream_security_api_key.fingerprint
  description = "API key fingerprint - Stream Security receives this automatically."
}

output "stream_security_status" {
  value       = "API key uploaded and acknowledgement POSTed to Stream Security. Status should flip to PENDING within ~1 minute."
  description = "Status hint for the customer."
}

# ---------------------------------------------------------------------------
# Ongoing audit-event pipeline (v1.2.0+).
# Events rule -> ONS topic -> HTTPS subscription -> Stream Security webhook.
# ---------------------------------------------------------------------------

resource "oci_ons_notification_topic" "stream_security_events_topic" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-events-${var.external_id}"
  description    = "Stream Security ongoing audit-event delivery topic."
}

resource "oci_ons_subscription" "stream_security_events" {
  compartment_id = var.tenancy_ocid
  topic_id       = oci_ons_notification_topic.stream_security_events_topic.id
  protocol       = "CUSTOM_HTTPS"
  endpoint       = var.events_url
}

# Match every audit event from the three OCI services that cover our 6 MVP
# resource types. Filtering down to specific event types happens inside
# Stream Security via the per-resource change_track_keys map — keeping the
# rule broad means future resource-type additions don't require a customer-
# side stack update.
resource "oci_events_rule" "stream_security_audit_events" {
  compartment_id = var.tenancy_ocid
  display_name   = "stream-security-audit-events-${var.external_id}"
  description    = "Forward OCI Compute/Network/Identity audit events to Stream Security."
  is_enabled     = true
  condition = jsonencode({
    eventType = [
      # Compute lifecycle (oci_instance)
      "com.oraclecloud.computeapi.launchinstance",
      "com.oraclecloud.computeapi.terminateinstance",
      "com.oraclecloud.computeapi.updateinstance",
      "com.oraclecloud.computeapi.instanceaction",
      # Virtual Network (oci_vcn, oci_subnet)
      "com.oraclecloud.virtualnetwork.createvcn",
      "com.oraclecloud.virtualnetwork.deletevcn",
      "com.oraclecloud.virtualnetwork.updatevcn",
      "com.oraclecloud.virtualnetwork.createsubnet",
      "com.oraclecloud.virtualnetwork.deletesubnet",
      "com.oraclecloud.virtualnetwork.updatesubnet",
      "com.oraclecloud.virtualnetwork.changesubnetcompartment",
      # Identity (oci_user, oci_policy, oci_compartment)
      "com.oraclecloud.identitycontrolplane.createuser",
      "com.oraclecloud.identitycontrolplane.deleteuser",
      "com.oraclecloud.identitycontrolplane.updateuser",
      "com.oraclecloud.identitycontrolplane.updateuserstate",
      "com.oraclecloud.identitycontrolplane.updateusercapabilities",
      "com.oraclecloud.identitycontrolplane.createpolicy",
      "com.oraclecloud.identitycontrolplane.deletepolicy",
      "com.oraclecloud.identitycontrolplane.updatepolicy",
      "com.oraclecloud.identitycontrolplane.createcompartment",
      "com.oraclecloud.identitycontrolplane.deletecompartment",
      "com.oraclecloud.identitycontrolplane.updatecompartment",
      "com.oraclecloud.identitycontrolplane.movecompartment",
    ]
  })
  actions {
    actions {
      action_type = "ONS"
      is_enabled  = true
      topic_id    = oci_ons_notification_topic.stream_security_events_topic.id
    }
  }
}
