# Stream Security OCI integration - Resource Manager stack v1.1.0
#
# Fully automated onboarding: Stream Security generates the API keypair
# server-side, sends the PUBLIC half via zipUrlVariables, this stack uploads
# it as the new IAM user's API key. An OCI Events rule fires on
# CreateApiKey, routes the event through OCI Notifications, which POSTs to
# Stream Security's auto-ack webhook. Customer clicks Apply and walks away.
#
# The private key never leaves Stream Security - only the public half
# enters your tenancy.

terraform {
  required_version = ">= 1.3"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = ">= 5.0.0"
    }
  }
}

# Resource Manager auto-populates these from the launching user's session.
variable "tenancy_ocid" {
  type        = string
  description = "Tenancy OCID (auto-populated by Resource Manager)."
}

variable "current_user_ocid" {
  type        = string
  description = "Launching user's OCID (auto-populated by Resource Manager; unused)."
}

variable "region" {
  type        = string
  description = "OCI region (auto-populated by Resource Manager)."
}

# Passed by Stream Security wizard via zipUrlVariables.
variable "external_id" {
  type        = string
  description = "Stream Security account identifier."
}

variable "account_token" {
  type        = string
  sensitive   = true
  description = "Stream Security per-account token (echoed in outputs)."
}

variable "public_key" {
  type        = string
  description = "PEM-encoded RSA public key generated by Stream Security; uploaded as the API key."
}

variable "acknowledge_url" {
  type        = string
  description = "Stream Security auto-ack HTTPS endpoint (with account_token in path)."
}

provider "oci" {
  region = var.region
}

# ---------------------------------------------------------------------------
# IAM: read-only user + group + policy + API key (using customer-supplied key)
# ---------------------------------------------------------------------------

resource "oci_identity_group" "stream_security_readers" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-readers-${var.external_id}"
  description    = "Stream Security read access."
}

resource "oci_identity_user" "stream_security_api_user" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-api-${var.external_id}"
  description    = "API-only user used by Stream Security to scan this tenancy."
  email          = "noreply+${var.external_id}@stream.security"
}

resource "oci_identity_user_group_membership" "stream_security_membership" {
  user_id  = oci_identity_user.stream_security_api_user.id
  group_id = oci_identity_group.stream_security_readers.id
}

resource "oci_identity_policy" "stream_security_read_policy" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-read-policy-${var.external_id}"
  description    = "Read-only access for Stream Security."
  statements = [
    "Allow group ${oci_identity_group.stream_security_readers.name} to inspect all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read all-resources in tenancy",
    "Allow group ${oci_identity_group.stream_security_readers.name} to read audit-events in tenancy",
  ]
}

resource "oci_identity_api_key" "stream_security_api_key" {
  user_id   = oci_identity_user.stream_security_api_user.id
  key_value = var.public_key
}

# ---------------------------------------------------------------------------
# Auto-ack: Notifications Topic + HTTPS subscription + Events rule
# ---------------------------------------------------------------------------

resource "oci_ons_notification_topic" "stream_security_topic" {
  compartment_id = var.tenancy_ocid
  name           = "stream-security-ack-${var.external_id}"
  description    = "Stream Security onboarding callback topic."
}

resource "oci_ons_subscription" "stream_security_ack" {
  compartment_id = var.tenancy_ocid
  topic_id       = oci_ons_notification_topic.stream_security_topic.id
  protocol       = "CUSTOM_HTTPS"
  endpoint       = var.acknowledge_url
}

resource "oci_events_rule" "stream_security_apikey_created" {
  compartment_id = var.tenancy_ocid
  display_name   = "stream-security-apikey-created-${var.external_id}"
  description    = "Forward Stream Security user's CreateApiKey events to the ack topic."
  is_enabled     = true
  condition = jsonencode({
    eventType = ["com.oraclecloud.identityControlPlane.CreateApiKey"]
    data = {
      resourceName = ["stream-security-api-${var.external_id}"]
    }
  })
  actions {
    actions {
      action_type = "ONS"
      is_enabled  = true
      topic_id    = oci_ons_notification_topic.stream_security_topic.id
    }
  }
  depends_on = [oci_ons_subscription.stream_security_ack, oci_identity_api_key.stream_security_api_key]
}

# ---------------------------------------------------------------------------
# Outputs (auto-ack handles everything; outputs are informational fallback).
# ---------------------------------------------------------------------------

output "stream_security_user_ocid" {
  value       = oci_identity_user.stream_security_api_user.id
  description = "OCI user OCID - Stream Security receives this automatically via the auto-ack webhook."
}

output "stream_security_fingerprint" {
  value       = oci_identity_api_key.stream_security_api_key.fingerprint
  description = "API key fingerprint - Stream Security receives this automatically via the auto-ack webhook."
}

output "stream_security_status" {
  value       = "Auto-ack subscription created. Stream Security should mark the integration READY within ~1 minute."
  description = "Status hint for the customer."
}
